question_data =  [{"category": "Geography", "type": "boolean", "difficulty": "easy",
                                                  "question": "Greenland is covered with grass and Iceland covered with ice.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                                  "question": "San Marino is the only country completely surrounded by another country.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Science: Computers", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "Donkey Kong was originally set to be a Popeye arcade game.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "History", "type": "boolean", "difficulty": "easy",
                                                  "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Science & Nature", "type": "boolean",
                                                  "difficulty": "easy", "question": "Salt is 100% composed of Sodium.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "General Knowledge", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "You can legally drink alcohol while driving in Mississippi.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                                                  "question": "A flock of crows is known as a homicide.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Entertainment: Comics", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "The &quot;Pepe&quot; meme originated from a comic drawn by Matt Furie called &quot;Boy&#039;s Club&quot;?",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Science: Computers", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Music", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "The song &quot;Stronger Than You&quot; is a single by Estelle, who played Garnet in Steven Universe.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Music", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "A Saxophone is a brass instrument.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Entertainment: Television", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "Klingons express emotion in art through opera and poetry.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Science & Nature", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "An average human can go two weeks without water.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; was released in 2004.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Music", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "Michael Jackson wrote The Simpsons song &quot;Do the Bartman&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                                  "question": "Nova Scotia is on the east coast of Canada.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Science: Mathematics", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "An equilateral triangle always has every angle measuring 60&deg;.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "Doki Doki Literature Club was developed in Japan.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]}]
